apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels: 
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - image: wil42/playground:v2
          name: playground
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground
spec:
  ports:
  - port: 8080
    targetPort: 8888
  selector:
    app: playground

