
Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64" # Latest stable Debian release
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end
  config.vm.hostname = "yrignyS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get install -y curl
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
    sudo chown vagrant:vagrant /etc/rancher/k3s/k3s.yaml
    sudo chmod 644 /etc/rancher/k3s/k3s.yaml
    echo 'export PATH=$PATH:/usr/local/bin' >> /home/vagrant/.bashrc
    echo 'alias k=kubectl' >> /home/vagrant/.bashrc
    kubectl apply -f /vagrant/deployment.yaml
    kubectl apply -f /vagrant/ingress.yaml
  SHELL

end
