# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64" # Latest stable Debian release
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1 # Minumum 2 CPUs for K3s server
    v.memory = 1024 # Minimum 2GB RAM for K3s server
  end
  
  config.vm.define "server" do |server|
    server.vm.hostname = "yrignyS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
      mkdir -p /vagrant/shared
      cp /var/lib/rancher/k3s/server/node-token /vagrant/shared/token
      sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      echo 'export PATH=$PATH:/usr/local/bin' >> /home/vagrant/.bashrc
      echo 'alias k=kubectl' >> /home/vagrant/.bashrc
    SHELL
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "yrignySW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", inline: <<-SHELL
      TOKEN=$(cat /vagrant/shared/token)
      sudo apt-get update && sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN INSTALL_K3S_EXEC="--node-ip=192.168.56.111" sh -
      echo 'export PATH=$PATH:/usr/local/bin' >> /home/vagrant/.bashrc
    SHELL
  end

end
