Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64" # Latest stable Debian release
  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
    v.memory = 8192
  end

  config.vm.hostname = "bonus"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", path: "scripts/install.sh"

end
